openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
tags:
  - name: StashSettingRoute
    description: 스태시 설정 관련 API
  - name: AuthRoute
    description: 인증 관련 API
paths:
  /oauth/google:
    get:
      description: 구글 OAuth 인증
      tags:
        - AuthRoute
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"
  /refresh-tokens:
    post:
      description: 토큰 갱신
      tags:
        - AuthRoute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenDto'
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"
        401:
          description: 인증 실패. 처음부터 다시 인증합니다.
  /stash-setting:
    get:
      description: 나의 스태시 설정 조회
      tags:
        - StashSettingRoute
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StashSettingDto"
  /stash-setting/update:
    put:
      description: 나의 스태시 설정 수정
      tags:
        - StashSettingRoute
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StashSettingDto'
      responses:
        200:
          description: 성공

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TokenDto:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          description: 액세스 토큰
        refreshToken:
          type: string
          description: 리프레시 토큰
    StashSettingDto:
      type: object
      properties:
        globalRule:
          $ref: '#/components/schemas/StashRule'
        whitelistUrls:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/StashRule'
    StashRule:
      type: object
      required:
        - idleCondition
        - idleTimeout
        - mutedTabIgnored
        - pinnedTabAllowed
      properties:
        idleCondition:
          type: string
          description: 유휴 상태로 취급할 윈도우 상태
        idleTimeout:
          type: integer
          format: int32
          description: 유휴 상태로 판단할 시간 (분)
        mutedTabIgnored:
          type: boolean
          description: 음소거된 탭 무시 여부
        containerTabIgnored:
          type: boolean
          nullable: true
          description: 컨테이너 탭 무시 여부
        pinnedTabAllowed:
          type: boolean
          description: 고정된 탭 허용 여부
