name: Build Check

on:
  pull_request:
    types:
      - opened
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    retry: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
